### ISSUE TITLE
Support for GSM player?

### ISSUE THREAD

**Issue by mustardseed312** [GValiente/butano#63]
Any chance that support for GSM player [https://github.com/pinobatch/gsmplayer-gba/tree/master](url) could be added down the road? I'm interested in making some rhythm games using music that's not possible using tracker files. Thanks for the amazing engine!

**Comment by GValiente** [comment]
For now I don't plan to support it because:
- Maxmod (library used by Butano to play DirectSound music and sound effects) doesn't allow to be stopped, so you couldn't use GSM Player after playing a tracker file. You would have to choose between Maxmod and GSM Player at build time.
- AFAIK GSM Player doesn't allow to play sound effects, only music.
- AFAIK GSM Player and Maxmod can't be used at the same time. If it would be possible to use them at the same time, previous issues would not matter, and I would probably look into adding support for GSM Player.

**Comment by GValiente** [comment]
Closed due to lack of activity.
