### ISSUE TITLE
I need butano.hpp

### ISSUE THREAD

**Issue by ibr0415** [GValiente/butano#77]
I'm trying to build a GBA file. Whenever i try and make it, i get an error saying that "butano.hpp: No such file or directory". Is butano.hpp supposed to be included already in the butano download, if so where exactly is it supposed to be at, because when i downloaded the zip, I can't find butano.hpp anywhere.

**Comment by GValiente** [comment]
Why do you think that butano.hpp header is supposed to be included in the butano download?

**Comment by GValiente** [comment]
Butano has never had a file with that name.

**Comment by ibr0415** [comment]
Damn. Am I cooked?!

**Comment by ycm** [comment]
> I'm trying to build a GBA file. Whenever i try and make it, i get an error saying that "butano.hpp: No such file or directory".

I'm not sure where you got your `make` command from, but if you follow the directions on the readme and the docs, you shouldn't ever run into a problem with `butano.hpp: No such file or directory` . The engine provides you with a `Makefile`, so you should use that.

Just go to the repo homepage and follow the instructions on *Getting Started*. There's a link to the Butano documentation as well, which should solve the issue.

> i downloaded the zip

After following the steps and getting a successful compile, if you'd like to start using the engine for your own projects, you might consider cloning the repo instead of downloading a zip. You can see from the commit history that the engine is constantly getting improvements and fixes. (And it's far easier to clone than download)

**Comment by ibr0415** [comment]
Ok i'll try that. Thank you for your help. Happy Thanksgiving. God did
